name: Go Get Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Once per week, Mondays at midnight
  workflow_dispatch: {}

jobs:
  update:
    name: Go Get Update
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Branch
        uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
        with:
          branch: automation/tools/go-get-update

      - shell: bash
        run: |
          go get -u ./...
          go mod tidy

      - name: Commit
        id: commit
        uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
        with:
          message: "Running 'go get -u ./...'"
          pathspec: "."
          keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
          key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

      - name: Push Branch
        if: ${{ steps.commit.outputs.commit_sha != '' }}
        uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
        with:
          branch: automation/tools/go-get-update

      - name: Open Pull Request
        if: ${{ steps.commit.outputs.commit_sha != '' }}
        uses: paketo-buildpacks/github-config/actions/pull-request/open@main
        with:
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
          title: "Running 'go get -u ./...'"
          branch: automation/tools/go-get-update

  failure:
    name: Alert on Failure
    runs-on: ubuntu-22.04
    needs: [update]
    if: ${{ always() && needs.update.result == 'failure' }}
    steps:
      - name: File Failure Alert Issue
        uses: paketo-buildpacks/github-config/actions/issue/file@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          label: "failure:go-get-update"
          comment_if_exists: true
          issue_title: "Failure: Go get update workflow"
          issue_body: |
            Go get update workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
          comment_body: |
            Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
