name: Update dependencies

on:
  schedule:
  - cron: '15 */1 * * *'
  workflow_dispatch: {}

concurrency: dependency_update

jobs:
  update-dependencies:
    runs-on: ubuntu-22.04
    name: Update dependencies
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/dependencies/update

    - name: Update dependencies
      id: update
      uses: paketo-buildpacks/github-config/actions/dependency/update@main

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Updating dependencies in buildpack.toml"
        pathspec: "."
        keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
        key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/dependencies/update

    - name: PR Title
      id: title
      if: ${{ steps.update.outputs.new-versions != '' }}
      run: |
        echo "::set-output name=include_versions:: with new dependency versions: ${{ steps.update.outputs.new-versions }}"

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Updates buildpack.toml${{ steps.title.outputs.include_versions }}"
        branch: automation/dependencies/update
